### ISSUE TITLE
Undefined index: HTTP_ACCEPT_LANGUAGE

### ISSUE THREAD

**Issue by strausmann** [pleinx/php-multilang-any#15]
We got this Message when our project will be execute via curl or cli.

pleinx/php-multilang-any/src/TranslatorAPI.php in MultilangAny\TranslatorAPI::getBrowserLanguage at line 118

![image](https://user-images.githubusercontent.com/4519228/76120776-7fdaee00-5ff2-11ea-8484-2e6100c35263.png)

**Comment by pleinx** [comment]
Hi @strausmann.

if you set no language countryIso via `TranslaterSettings`, GET-Parameter or $_SESSION then it will fallback into browser language in your case (cURL / CLI) you have no real client with language.

You have two options:

1) you can try to set the language header via cURL:   
`CURLOPT_HTTPHEADER     => array("Accept-Language: en-US;q=0.6,en;q=0.4"),`
Source: https://stackoverflow.com/a/16833250

2) set the language key via `TranslaterSettings`:

``` 
$settings = (new TranslatorSettings())
    ->setIsProduction(false)
    ->setLanguage('YOUR_LANGUAGE_CODE_HERE') // e. g. 'de' 'en'
    ->setFallbackLanguage('en')
    ->setLanguageFilesPath(__DIR__ . '/lang');

new TranslatorAPI($settings);
```

I would recommend option 2). In CLI mode you can add something linke
`$ php translate.php -lang=de`

your cli-script:
```
$language = $argv[1] ?? null;
$fallbackLanguage = 'en';

if($language === null) {
        $language = $fallbackLanguage;
}
else {
        $languageExploded = explode('=', $language);

        if($languageExploded[0] === '-lang' && !empty($languageExploded[1])) {
                $language = $languageExploded[1];
        }
        else {
                $language = $fallbackLanguage;
        }
}

$settings = (new TranslatorSettings())
    ->setIsProduction(false)
    ->setLanguage($language)
    ->setFallbackLanguage($fallbackLanguage)
    ->setLanguageFilesPath(__DIR__ . '/lang');

new TranslatorAPI($settings);

**Comment by strausmann** [comment]
Hello,

thank you for the very fast answer... :-)

I had hoped in the code this would be fixed directly. Say a check if $_SERVER['HTTP_ACCEPT_LANGUAGE'] is present, if not, just return NULL and pull the Fallback Language.

in my case a web cronjob is executed via Plesk. Plesk uses curl to call the URL. Alternatively I just found the solution of the .curlrc file in the Plesk user's homedir.

I would appreciate the change if you check for the existence of $_SERVER['HTTP_ACCEPT_LANGUAGE'].

Best Regards,

Bjoern

**Comment by pleinx** [comment]
Ah - now i get you!
Can you please checkout the v1.0.1?
